#!/bin/bash
set -e
if [[ -z ${GIT_DIR} ]]; then
  DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  GIT_DIR="${DIR}/.."
fi
for hook in ${GIT_DIR}/../funny_shell/git/hooks/*; do
  echo "execute hook: ${hook}."
  ${hook}
done
